= Cheatsheets

[[ClientDestination]]
== ClientDestination

++++
 Defines the HTTP Repository connection destination.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[domain]]`@domain`|`String`|+++
Set the domain of the http repository. This could be either a domain or the IP of the host:
 e.g. <code>localhost</code> or  <code>10.0.11.2</code>.
+++
|[[hostHeader]]`@hostHeader`|`String`|+++
Set the host header override to be used with a communication to the repository. If it's set, it
 overrides any value in the <code>'Host'</code> header, and sets the SNI SSL to the same value.
+++
|[[port]]`@port`|`Number (int)`|+++
Set the HTTP port of the http repository.
+++
|[[scheme]]`@scheme`|`String`|+++
Set the URL scheme used to communicate with the repository. Should be set to <code>http</code> or
 <code>https</code>.
+++
|===

[[CustomHttpHeaderOptions]]
== CustomHttpHeaderOptions

++++
 Describes a custom header that is send with every HTTP Repository request.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[name]]`@name`|`String`|+++
Name of the request header.
+++
|[[value]]`@value`|`String`|+++
Value of the request header.
+++
|===

[[HttpRepositoryOptions]]
== HttpRepositoryOptions

++++
 HTTP Repository connector configuration
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[allowedRequestHeaders]]`@allowedRequestHeaders`|`Array of String`|+++
Set the collection of patterns of allowed request headers. Only headers matching any of the
 pattern from the set will be sent to the HTTP repository. Each item is a string that defines
 regex, e.g. to match any char use <code>.*</code>.
+++
|[[clientDestination]]`@clientDestination`|`link:dataobjects.html#ClientDestination[ClientDestination]`|+++
Set the remote location of the repository.
+++
|[[clientOptions]]`@clientOptions`|`link:dataobjects.html#WebClientOptions[WebClientOptions]`|+++
Set the <code>WebClientOptions</code> used by the HTTP client to communicate with remote http
 repository. See https://vertx.io/docs/vertx-web-client/dataobjects.html#WebClientOptions for
 the details what can be configured.
+++
|[[customHttpHeader]]`@customHttpHeader`|`link:dataobjects.html#CustomHttpHeaderOptions[CustomHttpHeaderOptions]`|+++
Set the header (name and value) to be sent in every request to the remote repository.
+++
|===

